[workspace]
members = [
    "easyshare-server",
    "easyshare-cron",
]
resolver = "2"

[workspace.dependencies]
worker = "0.0.18"
cfg-if = "1"

[profile.release]
lto = true
strip = true
codegen-units = 1
